server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Отобразит в логах все sql запросы
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #Преобразить Java в байты
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #Преобразить в байты
      properties:
        spring.json.add.type.headers: false #избежать ошибку несопадения имен при добавлении метаданных
kafka:
  partitions: 3
logging:
  level: #два уровня дебаггинга
    com.alexnosevichdev.orders: DEBUG
    org.apache.kafka: WARN
